mod e2e;

e2e::e2e_test_cases!(
    "tests/e2e/cases",
    case_001_simple_passthrough => "001_simple_passthrough",
    case_002_ifelse_true_branch => "002_ifelse_true_branch",
    case_003_template_transform => "003_template_transform",
    case_004_ifelse_false_branch => "004_ifelse_false_branch",
    case_005_ifelse_multi_case => "005_ifelse_multi_case",
    case_006_ifelse_or_logic => "006_ifelse_or_logic",
    case_007_answer_node => "007_answer_node",
    case_008_code_node_js => "008_code_node_js",
    case_009_code_string_ops => "009_code_string_ops",
    case_010_variable_aggregator => "010_variable_aggregator",
    case_011_template_multi_vars => "011_template_multi_vars",
    case_012_chain_pipeline => "012_chain_pipeline",
    case_013_max_steps_exceeded => "013_max_steps_exceeded",
    case_014_multiple_inputs => "014_multiple_inputs",
    case_015_ifelse_string_conditions => "015_ifelse_string_conditions",
    case_016_ifelse_null_check => "016_ifelse_null_check",
    case_017_answer_with_code => "017_answer_with_code",
    case_018_code_json_output => "018_code_json_output",
    case_019_partial_match => "019_partial_match",
    case_020_system_variables => "020_system_variables",
    case_021_ifelse_and_multi_cond => "021_ifelse_and_multi_cond",
    case_022_ifelse_and_fail => "022_ifelse_and_fail",
    case_023_template_jinja2_conditional => "023_template_jinja2_conditional",
    case_024_template_jinja2_loop => "024_template_jinja2_loop",
    case_025_empty_workflow => "025_empty_workflow",
    case_026_ifelse_empty_check => "026_ifelse_empty_check",
    case_027_fake_time_and_id => "027_fake_time_and_id",
    case_028_ifelse_in_operator => "028_ifelse_in_operator",
    case_029_aggregator_fallback => "029_aggregator_fallback",
    case_030_code_boolean_return => "030_code_boolean_return",
    case_031_http_get_basic => "031_http_get_basic",
    case_032_http_post_json => "032_http_post_json",
    case_033_http_custom_headers => "033_http_custom_headers",
    case_034_http_bearer_auth => "034_http_bearer_auth",
    case_035_http_basic_auth => "035_http_basic_auth",
    case_036_http_error_status => "036_http_error_status",
    case_037_http_post_raw_text => "037_http_post_raw_text",
    case_038_http_put_method => "038_http_put_method",
    case_039_http_delete_method => "039_http_delete_method",
    case_040_http_server_error => "040_http_server_error",
    case_041_http_patch_method => "041_http_patch_method",
    case_042_http_with_code_pipeline => "042_http_with_code_pipeline",
    case_043_http_ifelse_status => "043_http_ifelse_status",
    case_044_http_no_auth => "044_http_no_auth",
    case_045_js_builtins => "045_js_builtins",
    case_046_code_node_wasm => "046_code_node_wasm",
    case_048_llm_openai_basic => "048_llm_openai_basic",
    case_049_error_handler_recover => "049_error_handler_recover",
    case_057_llm_stream_basic => "057_llm_stream_basic",
    case_058_llm_stream_answer => "058_llm_stream_answer",
    case_059_llm_stream_template => "059_llm_stream_template",
    case_060_llm_stream_code_callback => "060_llm_stream_code_callback",
    case_061_llm_stream_code_autocollect => "061_llm_stream_code_autocollect",
    case_062_llm_stream_aggregator => "062_llm_stream_aggregator",
    case_063_llm_stream_chain => "063_llm_stream_chain",
    case_064_llm_stream_ifelse => "064_llm_stream_ifelse",
    case_065_llm_stream_multi_chunk => "065_llm_stream_multi_chunk",
    case_066_llm_stream_template_mixed => "066_llm_stream_template_mixed",
    case_067_llm_stream_answer_mixed => "067_llm_stream_answer_mixed",
    case_068_llm_stream_code_template => "068_llm_stream_code_template",
    case_069_llm_stream_end_collect => "069_llm_stream_end_collect",
    case_070_llm_stream_single_chunk => "070_llm_stream_single_chunk",
    case_071_llm_stream_assigner => "071_llm_stream_assigner",
    case_072_llm_stream_http => "072_llm_stream_http",
    case_073_llm_stream_dual_answer => "073_llm_stream_dual_answer",
    case_074_llm_stream_code_counter => "074_llm_stream_code_counter",
);

#[cfg(feature = "plugin-system")]
e2e::e2e_test_cases!(
    "tests/e2e/cases",
    case_047_plugin_node_basic => "047_plugin_node_basic",
    case_075_plugin_host_node_basic => "075_plugin_host_node_basic",
    case_076_plugin_bootstrap_sandbox => "076_plugin_bootstrap_sandbox",
    case_077_plugin_llm_provider => "077_plugin_llm_provider",
    case_078_plugin_hook_modifier => "078_plugin_hook_modifier",
);

e2e::e2e_debug_test_cases!(
    "tests/e2e/cases",
    case_050_debug_break_on_start => "050_debug_break_on_start",
    case_051_debug_step_through => "051_debug_step_through",
    case_052_debug_breakpoint_hit => "052_debug_breakpoint_hit",
    case_053_debug_update_variables => "053_debug_update_variables",
    case_054_debug_abort => "054_debug_abort",
    case_055_debug_dynamic_breakpoint => "055_debug_dynamic_breakpoint",
    case_056_debug_branch_breakpoint => "056_debug_branch_breakpoint",
);
