#![cfg(all(
    feature = "plugin-system",
    feature = "builtin-sandbox-js",
    feature = "builtin-sandbox-wasm",
    feature = "builtin-template-jinja",
    feature = "builtin-core-nodes",
    feature = "builtin-transform-nodes",
    feature = "builtin-http-node",
    feature = "builtin-code-node",
    feature = "builtin-subgraph-nodes",
    feature = "builtin-llm-node",
))]

mod integration;

integration::integration_test_cases!(
    "tests/integration/cases",
    case_001_simple_passthrough => "001_simple_passthrough",
    case_002_ifelse_true_branch => "002_ifelse_true_branch",
    case_003_template_transform => "003_template_transform",
    case_004_ifelse_false_branch => "004_ifelse_false_branch",
    case_005_ifelse_multi_case => "005_ifelse_multi_case",
    case_006_ifelse_or_logic => "006_ifelse_or_logic",
    case_007_answer_node => "007_answer_node",
    case_008_code_node_js => "008_code_node_js",
    case_009_code_string_ops => "009_code_string_ops",
    case_010_variable_aggregator => "010_variable_aggregator",
    case_011_template_multi_vars => "011_template_multi_vars",
    case_012_chain_pipeline => "012_chain_pipeline",
    case_013_max_steps_exceeded => "013_max_steps_exceeded",
    case_014_multiple_inputs => "014_multiple_inputs",
    case_015_ifelse_string_conditions => "015_ifelse_string_conditions",
    case_016_ifelse_null_check => "016_ifelse_null_check",
    case_017_answer_with_code => "017_answer_with_code",
    case_018_code_json_output => "018_code_json_output",
    case_019_partial_match => "019_partial_match",
    case_020_system_variables => "020_system_variables",
    case_021_ifelse_and_multi_cond => "021_ifelse_and_multi_cond",
    case_022_ifelse_and_fail => "022_ifelse_and_fail",
    case_023_template_jinja2_conditional => "023_template_jinja2_conditional",
    case_024_template_jinja2_loop => "024_template_jinja2_loop",
    case_025_empty_workflow => "025_empty_workflow",
    case_026_ifelse_empty_check => "026_ifelse_empty_check",
    case_027_fake_time_and_id => "027_fake_time_and_id",
    case_028_ifelse_in_operator => "028_ifelse_in_operator",
    case_029_aggregator_fallback => "029_aggregator_fallback",
    case_030_code_boolean_return => "030_code_boolean_return",
    case_031_http_get_basic => "031_http_get_basic",
    case_032_http_post_json => "032_http_post_json",
    case_033_http_custom_headers => "033_http_custom_headers",
    case_034_http_bearer_auth => "034_http_bearer_auth",
    case_035_http_basic_auth => "035_http_basic_auth",
    case_036_http_error_status => "036_http_error_status",
    case_037_http_post_raw_text => "037_http_post_raw_text",
    case_038_http_put_method => "038_http_put_method",
    case_039_http_delete_method => "039_http_delete_method",
    case_040_http_server_error => "040_http_server_error",
    case_041_http_patch_method => "041_http_patch_method",
    case_042_http_with_code_pipeline => "042_http_with_code_pipeline",
    case_043_http_ifelse_status => "043_http_ifelse_status",
    case_044_http_no_auth => "044_http_no_auth",
    case_045_js_builtins => "045_js_builtins",
    case_046_code_node_wasm => "046_code_node_wasm",
    case_048_llm_openai_basic => "048_llm_openai_basic",
    case_049_error_handler_recover => "049_error_handler_recover",
    case_057_llm_stream_basic => "057_llm_stream_basic",
    case_058_llm_stream_answer => "058_llm_stream_answer",
    case_059_llm_stream_template => "059_llm_stream_template",
    case_060_llm_stream_code_callback => "060_llm_stream_code_callback",
    case_061_llm_stream_code_autocollect => "061_llm_stream_code_autocollect",
    case_062_llm_stream_aggregator => "062_llm_stream_aggregator",
    case_063_llm_stream_chain => "063_llm_stream_chain",
    case_064_llm_stream_ifelse => "064_llm_stream_ifelse",
    case_065_llm_stream_multi_chunk => "065_llm_stream_multi_chunk",
    case_066_llm_stream_template_mixed => "066_llm_stream_template_mixed",
    case_067_llm_stream_answer_mixed => "067_llm_stream_answer_mixed",
    case_068_llm_stream_code_template => "068_llm_stream_code_template",
    case_069_llm_stream_end_collect => "069_llm_stream_end_collect",
    case_070_llm_stream_single_chunk => "070_llm_stream_single_chunk",
    case_071_llm_stream_assigner => "071_llm_stream_assigner",
    case_072_llm_stream_http => "072_llm_stream_http",
    case_073_llm_stream_dual_answer => "073_llm_stream_dual_answer",
    case_074_llm_stream_code_counter => "074_llm_stream_code_counter",
    case_079_iteration_sequential => "079_iteration_sequential",
    case_080_iteration_parallel => "080_iteration_parallel",
    case_081_iteration_error_terminated => "081_iteration_error_terminated",
    case_082_iteration_error_remove_abnormal => "082_iteration_error_remove_abnormal",
    case_083_iteration_error_continue => "083_iteration_error_continue",
    case_084_iteration_max_exceeded => "084_iteration_max_exceeded",
    case_085_loop_basic => "085_loop_basic",
    case_086_loop_max_exceeded => "086_loop_max_exceeded",
    case_087_loop_type_mismatch_break => "087_loop_type_mismatch_break",
    case_088_list_op_simple => "088_list_op_simple",
    case_089_list_op_sort_slice => "089_list_op_sort_slice",
    case_090_list_op_filter => "090_list_op_filter",
    case_091_list_op_map => "091_list_op_map",
    case_092_list_op_reduce => "092_list_op_reduce",
    case_093_assigner_overwrite => "093_assigner_overwrite",
    case_094_assigner_append => "094_assigner_append",
    case_095_assigner_clear => "095_assigner_clear",
    case_096_error_strategy_fail_branch => "096_error_strategy_fail_branch",
    case_097_error_strategy_default_value => "097_error_strategy_default_value",
    case_098_env_vars_in_workflow => "098_env_vars_in_workflow",
    case_099_conversation_vars => "099_conversation_vars",
    case_100_diamond_merge => "100_diamond_merge",
    case_101_code_js_syntax_error => "101_code_js_syntax_error",
    case_102_code_js_runtime_exception => "102_code_js_runtime_exception",
    case_103_code_no_main_function => "103_code_no_main_function",
    case_104_code_returns_non_object => "104_code_returns_non_object",
    case_105_template_missing_variable => "105_template_missing_variable",
    case_106_ifelse_missing_variable => "106_ifelse_missing_variable",
    case_107_aggregator_all_null => "107_aggregator_all_null",
    case_108_end_invalid_selector => "108_end_invalid_selector",
    case_109_error_strategy_none => "109_error_strategy_none",
    case_110_retry_success_on_second => "110_retry_success_on_second",
    case_111_retry_exhausted => "111_retry_exhausted",
    case_112_iteration_empty_list => "112_iteration_empty_list",
    case_113_loop_with_ifelse => "113_loop_with_ifelse",
    case_114_loop_break_first_check => "114_loop_break_first_check",
    case_115_env_in_ifelse => "115_env_in_ifelse",
    case_116_conversation_var_array => "116_conversation_var_array",
    case_117_error_handler_access_error_info => "117_error_handler_access_error_info",
    case_118_val_no_start_node => "118_val_no_start_node",
    case_119_val_cycle_detected => "119_val_cycle_detected",
    case_120_val_duplicate_node_id => "120_val_duplicate_node_id",
    case_121_security_resource_cpu_limit => "121_security_resource_cpu_limit",
    case_122_security_memory_limit => "122_security_memory_limit",
    case_123_security_network_ssrf => "123_security_network_ssrf",
    case_125_security_audit_logging => "125_security_audit_logging",
    case_127_security_sandbox_isolation => "127_security_sandbox_isolation",
    case_129_compiler_json_format => "129_compiler_json_format",
    case_131_compiler_empty_node_data => "131_compiler_empty_node_data",
    case_132_compiler_large_workflow => "132_compiler_large_workflow",
    case_133_plugin_bootstrap_phase => "133_plugin_bootstrap_phase",
    case_134_plugin_normal_phase => "134_plugin_normal_phase",
    case_135_plugin_hook_execution => "135_plugin_hook_execution",
    case_137_plugin_shutdown_lifecycle => "137_plugin_shutdown_lifecycle",
    case_138_error_retry_exponential_backoff => "138_error_retry_exponential_backoff",
    case_143_error_validation_missing_edge_target => "143_error_validation_missing_edge_target",
    case_144_error_retry_all_attempts_fail => "144_error_retry_all_attempts_fail",
    case_151_error_loop_condition_fail => "151_error_loop_condition_fail",
    case_159_advanced_diamond_complex_merge => "159_advanced_diamond_complex_merge",
    case_161_advanced_loop_state_management => "161_advanced_loop_state_management",
    case_165_advanced_parallel_sync => "165_advanced_parallel_sync",
    case_167_advanced_conversation_history => "167_advanced_conversation_history",
);

#[cfg(feature = "plugin-system")]
integration::integration_test_cases!(
    "tests/integration/cases",
    case_047_plugin_node_basic => "047_plugin_node_basic",
    case_075_plugin_host_node_basic => "075_plugin_host_node_basic",
    case_077_plugin_llm_provider => "077_plugin_llm_provider",
    case_078_plugin_hook_modifier => "078_plugin_hook_modifier",
);

integration::integration_debug_test_cases!(
    "tests/integration/cases",
    case_050_debug_break_on_start => "050_debug_break_on_start",
    case_051_debug_step_through => "051_debug_step_through",
    case_052_debug_breakpoint_hit => "052_debug_breakpoint_hit",
    case_053_debug_update_variables => "053_debug_update_variables",
    case_054_debug_abort => "054_debug_abort",
    case_055_debug_dynamic_breakpoint => "055_debug_dynamic_breakpoint",
    case_056_debug_branch_breakpoint => "056_debug_branch_breakpoint",
);
